### ISSUE TITLE
Unable to Install Python Package for Python 3.7.4 64bit

### ISSUE THREAD

**Issue by shobhit-coder** [Azure-Samples/blockchain#197]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Install Python 3.7.4 64 bit and run the setup.py in the python folder. and then run import swagger_client

### Any log messages given by the failure
>
Traceback (most recent call last):
  File "f:/codefundo2019/temp/helo.py", line 1, in <module>
    import swagger_client
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Users\SHOBHIT KUMAR.SHOBHIT-PC.000\AppData\Roaming\Python\Python37\site-packages\swagger_client-1.0.0-py3.7.egg\swagger_client\__init__.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Users\SHOBHIT KUMAR.SHOBHIT-PC.000\AppData\Roaming\Python\Python37\site-packages\swagger_client-1.0.0-py3.7.egg\swagger_client\api\__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 594, in spec_from_file_location
  File "C:\Users\SHOBHIT KUMAR.SHOBHIT-PC.000\AppData\Roaming\Python\Python37\site-packages\swagger_client-1.0.0-py3.7.egg\swagger_client\api\applications_api.py", line 121
    async=params.get('async'),
        ^
SyntaxError: invalid syntax
PS F:\codefundo2019\temp> & "C:/Program Files/Python37/python.exe" f:/codefundo2019/temp/helo.py
Traceback (most recent call last):
  File "f:/codefundo2019/temp/helo.py", line 1, in <module>
    import swagger_client
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Users\SHOBHIT KUMAR.SHOBHIT-PC.000\AppData\Roaming\Python\Python37\site-packages\swagger_client-1.0.0-py3.7.egg\swagger_client\__init__.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Users\SHOBHIT KUMAR.SHOBHIT-PC.000\AppData\Roaming\Python\Python37\site-packages\swagger_client-1.0.0-py3.7.egg\swagger_client\api\__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 594, in spec_from_file_location
  File "C:\Users\SHOBHIT KUMAR.SHOBHIT-PC.000\AppData\Roaming\Python\Python37\site-packages\swagger_client-1.0.0-py3.7.egg\swagger_client\api\applications_api.py", line 121
    async=params.get('async'),
        ^
SyntaxError: invalid syntax

### Expected/desired behavior
>
The package should have imported normally

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Window 10
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ramyapradhan** [comment]
Hello @shobhit-coder, please let us know if you are still running into this issue. 

Thanks!

**Comment by ramyapradhan** [comment]
Hello @shobhit-coder,

I am writing to inform you that I will be closing this issue since it has been open for over 30 days.  Please feel free to re-open this issue.

Thanks,
Ramya
