### ISSUE TITLE
Python package doesnt install on 3.6.5

### ISSUE THREAD

**Issue by shobhit-coder** [Azure-Samples/blockchain#198]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>run python setup.py install --user to install the package and then import swagger_client

### Any log messages given by the failure
>

### Expected/desired behavior
>
C:\blockchain\blockchain-workbench\rest-api-samples\python>python
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import swagger_client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\blockchain\blockchain-workbench\rest-api-samples\python\swagger_client\__init__.py", line 19, in <module>
    from swagger_client.api.applications_api import ApplicationsApi
  File "C:\blockchain\blockchain-workbench\rest-api-samples\python\swagger_client\api\__init__.py", line 6, in <module>
    from swagger_client.api.applications_api import ApplicationsApi
  File "C:\blockchain\blockchain-workbench\rest-api-samples\python\swagger_client\api\applications_api.py", line 21, in <module>
    from swagger_client.api_client import ApiClient
  File "C:\blockchain\blockchain-workbench\rest-api-samples\python\swagger_client\api_client.py", line 27, in <module>
    import swagger_client.models
  File "C:\blockchain\blockchain-workbench\rest-api-samples\python\swagger_client\models\__init__.py", line 52, in <module>
    from swagger_client.models.workflow import Workflow
  File "C:\blockchain\blockchain-workbench\rest-api-samples\python\swagger_client\models\workflow.py", line 19, in <module>
    from swagger_client.models.workflow_function import WorkflowFunction  # noqa: F401,E501
  File "C:\blockchain\blockchain-workbench\rest-api-samples\python\swagger_client\models\workflow_function.py", line 19, in <module>
    from swagger_client.models.workflow_function_parameter import WorkflowFunctionParameter  # noqa: F401,E501
  File "C:\blockchain\blockchain-workbench\rest-api-samples\python\swagger_client\models\workflow_function_parameter.py", line 19, in <module>
    from swagger_client.models.workflow_data_type import WorkflowDataType  # noqa: F401,E501
  File "C:\blockchain\blockchain-workbench\rest-api-samples\python\swagger_client\models\workflow_data_type.py", line 19, in <module>
    from swagger_client.models.workflow_data_type import WorkflowDataType  # noqa: F401,E501
ImportError: cannot import name 'WorkflowDataType'

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

Windows 10
### Versions
>

### Mention any other details that might be useful
I have tried installing the same in Python 3.7 as well. i have opened another thread for that
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ramyapradhan** [comment]
Hi @shobhit-coder,

I am writing to inform you that I will be closing this issue since you have opened another thread for this and also since it has been open for more than 30 days.  Please feel free to re-open this issue or track it on the other thread.

Thanks,
Ramya
