### ISSUE TITLE
Problem with ❝Delivering Data from IoT Hub to Azure Blockchain Workbench❞

### ISSUE THREAD

**Issue by mesgar** [Azure-Samples/blockchain#208]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Just followed the steps described in 
https://github.com/Azure-Samples/blockchain/blob/master/blockchain-workbench/iot-integration-samples/ConfigureIoTDemo.md
 and everything looks fine 
![image](https://user-images.githubusercontent.com/10726024/67539483-424d8680-f71d-11e9-84a3-d0726882810e.png)

but when I check it on ABW UI there is no activity from device.
I can log in as device in ABW UI and enter telemetry data.

![image](https://user-images.githubusercontent.com/10726024/67539638-b6882a00-f71d-11e9-8b81-f54e34bce487.png)
I also checked the database and couldn't find any data coming from device.
(only data ingested from UI was registered)
![image](https://user-images.githubusercontent.com/10726024/67540274-c274eb80-f71f-11e9-8c50-03a518fed8e6.png)

How can I debug this? 
Is there any log/information available after I send a message to "ingressQueue"?
 
### Versions
>
ABW  1.7.3

### Mention any other details that might be useful
Here is my data coming from device:
{"deviceid":"0fea776f-96b2-4ecf-9dd5-b48a78317c33","temperature": 28,"humidity": 76}
※as you see I use my on user external-id as deviceid.

Data send to queue:
{
    "requestId": "680de98d-09e9-4eb4-88a0-30523421b97e",
    "userChainIdentifier": "0xca2d7158d0780e2fe88e1f6d9b5518f131601c56",
    "contractLedgerIdentifier": "0xb4f3734cc97a11bb48ada02167025924cc8638d9",
    "workflowFunctionName": "IngestTelemetry",
    "Parameters": [
        {
            "name": "humidity",
            "value": "76"
        },
        {
            "name": "temperature",
            "value": "28"
        }
        {
            "name": "timestamp",
            "value": "1571969366"
        }
    ],
    "connectionId": "1",
    "messageSchemaVersion": "1.0.0",
    "messageName": "CreateContractActionRequest"
}
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mesgar** [comment]
Interesting behavior.
There was nothing wrong with logic app, and messaging. 

As you can see my device telemetry data was delivered to the blockchain every minute.
![image](https://user-images.githubusercontent.com/10726024/69434122-58804e00-0d80-11ea-9600-c23aedffb166.png)

In the meantime, i've created another contract (Id:37 ) for another device, and right after data delivery for contract id 36 seemed to be stopped!
![image](https://user-images.githubusercontent.com/10726024/69434284-a5fcbb00-0d80-11ea-8884-7377e67546eb.png)

So, it works perfectly when its on the top of the list. (contract id: 38)
but what happens when you have several tracks delivering ice cream to different destinations?
If i'm not getting it wrong, only last created contract has a chance to get real-time telemetry data.   
![image](https://user-images.githubusercontent.com/10726024/69434460-07248e80-0d81-11ea-9672-9702eaa78c24.png)

Is this an expected behavior?

**Comment by ramyapradhan** [comment]
Hello @mesgar,

This is not an expected behavior and you should be able to take an action on any contract, not just the first one on the top.  I will need more information to determine why exactly this is the case with your deployment.  I recommend doing an upgrade to the latest version of Workbench and see if the issue still persists.  Please do let me know on how this goes.

To your question on what happens if there are multiple trucks going to multiple destinations - you could have each truck and destination combination be individually tracked by a contract each.  These contracts will update automatically as and when there are updates to the contract state.  You can test this by creating two contracts, assign two different device ids to each, and go through the workflow to see how these contracts get updated.  Please let me know if you need more information.

Thanks,
Ramya

**Comment by manoj-ratnam** [comment]
@ramyapradhan  - I am following this link and have got the similar problem. I followed https://github.com/Azure-Samples/blockchain-devkit/tree/master/connect/iot/iot-central/blockchain-workbench to set up a IoT-Blockchain telemetry application, but the blockchain is not able to read the messages that are being fired from the logicapp into the service bus. 

My primary query is - as per this documentation, we need to point the logicapp to write into activityhub (queue), however, there was no activityhub (queue) in the Service Bus. Can you let us know from which queue does the Block Chain Workbench API reads and updated the ledger?

**Comment by mesgar** [comment]
@manoj-ratnam 
According to documents you should write your message to "ingressqueue".
Here is my setting.
![image](https://user-images.githubusercontent.com/10726024/75123575-00911480-56ec-11ea-9003-ce90244aa788.png)

![image](https://user-images.githubusercontent.com/10726024/75123594-2b7b6880-56ec-11ea-8fd1-8b8644bea751.png)

JSON 
"path": "/@{encodeURIComponent(encodeURIComponent('ingressqueue'))}/messages"

**Comment by mesgar** [comment]
@ramyapradhan 
Thanks for your comment Ramya.
I already upgraded my ABW but it didn't help.
![image](https://user-images.githubusercontent.com/10726024/75123938-105e2800-56ef-11ea-8176-5f4e79829a5c.png)

It's a BUG (or at least I assume it's a bug). 
Is it working for you? if its working for you then something is wrong  with my logic app code.
It would be helpful if you copy/paste your entire logic app code here.

**Comment by JackZ139** [comment]
Hi There, 

I am doing this sample currently but met some problem.
The problem is that I can't find the ingress queue when using send message.
Do you know how to solve it?
Also, if you are able to tell me you contact info, like WhatsApp, it would be better!
Thank you so much!

Jack

**Comment by mesgar** [comment]
Hello @JackZ139 
I'm not sure if they fixed the problem I faced, but here is what i know.
In Azure portal go to Resource group > Service Bus > Queue. 
If you could see the the ingress queue there, then there must be a problem with your connector to service bus in logic app.
Try to re-connect to service bus in ABW.

Regards,

**Comment by sgiovinetti** [comment]
Same issue here: No telemetry is ingested into workbench from the service bus
@mesgar : the issue of top contract persist and is due to a bug in the stored procedure you call in the logic app. This SP takes only the first contract order by timestamp (they do SELECT TOP 1). For let it works you need to refactor the SP to send out a json array instead of a single element and then adjust your logic app consequently.

Anyway apsrt from that bug the telemetry is not ingested so I'm afraid there is another more serious bug. Would be nice if someone from MS can investigate and fix it.

**Comment by sgiovinetti** [comment]
Tried different json input format but anyhow does not work. Here the one that by documentation should work but it doesn't.

![image](https://user-images.githubusercontent.com/24455693/107034086-818ad400-67b6-11eb-8cbc-77ad5bcc5ff6.png)

Here the plain json

{
  "requestId": "31be710c-5f3f-4414-a184-a461651a46dd",
  "userChainIdentifier": "0xccc...",
  "contractLedgerIdentifier": "0xd....",
  "workflowFunctionName": "IngestTelemetry",
  "Parameters": [
    { "name": "humidity", "value": "16" },
    { "name": "temperature", "value": "26" }
    { "name": "timestamp", "value": "1612527299" }
  ],
"connectionId":1 ,
    "messageSchemaVersion": "1.0.0",
    "messageName": "CreateContractActionRequest"
}

**Comment by mesgar** [comment]
@sgiovinetti @JackZ139

Regardless of issue itself, this can be done via REST API also:
https://medium.com/@malirezaie/how-to-enable-programmatic-interaction-with-azure-blockchain-workbench-apis-56c0d95c79c0

Wrote a step by step guide but you need to use google translator for this:
https://qiita.com/iCloudy/items/6e9af60012da64891561

and the project is here:
https://github.com/mesgar/ABWFunction

**Comment by sgiovinetti** [comment]
@mesgar I was thinking the same however I have another issue with the API. All API calls excpet the ones for users (api/VI/Users/*) replies me with 204 no content.

It looks like my service principle has no enought permissions within the API web application. Any clue how to solve it? Another anomaly I have is that if I login to the webapp with the user that impersonates the device the app tells me not authorized please ask an admin to allow you to login workbench. Any clue?

**Comment by sgiovinetti** [comment]
I think there is something wrong here. Both 3 scenarios failed:
1. Using queue: the queue is picked up by the webapp but nothing seems to happen. I checked with appinsights the logs but there is nothing about this message just random errors about some system GUIDs that are not in the correct format. It looks like an internal error that has nothing in common with my message.
2. Using the API with postman. Not clear which payload to use ([this](https://docs.microsoft.com/en-us/azure/blockchain/workbench/use-api) payload for 'contract action post request' is clearly wrong since it is not even a valid json). I tried correcting the json putting the indicated 'actionInformation' property as a top object  and sending it but I receive a 500 internal error. 
```
{"actionInformation": 
    {
        "workflowFunctionID": 2,
        "workflowActionParameters": [
            {
            "name": "humidity",
            "value": "15"
            },
            {
            "name": "temperature",
            "value": "25"
            },
            {
            "name": "timestamp",
            "value": "1612780547"
            }
        ]
    }
}
``` 
If I send the json without "actionInformation" object I receive a 404 bad request.
```
{
        "workflowFunctionID": 2,
        "workflowActionParameters": [
            {
            "name": "humidity",
            "value": "15"
            },
            {
            "name": "temperature",
            "value": "25"
            },
            {
            "name": "timestamp",
            "value": "1612780547"
            }
        ]
    }
```
3. I tried looking at the DB and calling the stored procedure CreateContractActionFromIngressQueue that at the end calls the SP CreateContractAction. At the end it seems that both the queue and API uses this stored procedure. The stored procedure runs successfully and I see a transaction in the app but for some unknown reason this trasaction is never mined and remains always in provisioning state 0 that means '0: Provisioned in the database at the API level, but doesn't have an address associated with it'

![image](https://user-images.githubusercontent.com/24455693/107241202-0b42d780-6a2b-11eb-8c83-d3687f9c3144.png)

![image](https://user-images.githubusercontent.com/24455693/107241353-34636800-6a2b-11eb-8537-499ba4a3eebd.png)

What I see in the app after the stored procedure call

![image](https://user-images.githubusercontent.com/24455693/107241582-696fba80-6a2b-11eb-8e41-9c9d15a365c0.png)


Frankly speaking have no idea what else to look at. I cannot ingest the device data into blockchain in any way. Any hint from someone at microsoft would be really appreciated.

**Comment by mesgar** [comment]
@sgiovinetti 
Did you check the logs for 500 internal error?
You can use Log stream on ABW App Service to get a little bit more detail on errors.

**Comment by mesgar** [comment]
@sgiovinetti 
I was able to send telemetry data via Rest API.
It need a little trick.

1st I created my contract like this.
![image](https://user-images.githubusercontent.com/10726024/107334045-94c0db00-6af9-11eb-9759-4acf5e67b44b.png)
 
then call the API and send the telemetry data.
![image](https://user-images.githubusercontent.com/10726024/107335736-a7d4aa80-6afb-11eb-9c1e-a554f41f3201.png)

Function output:
![image](https://user-images.githubusercontent.com/10726024/107335793-b7ec8a00-6afb-11eb-958b-13e33bbf8eee.png)

The Result:
![image](https://user-images.githubusercontent.com/10726024/107336455-74dee680-6afc-11eb-81cc-1d3c1fcf3413.png)

 **Put the source code here for your convenience:**
 [source code](https://github.com/mesgar/AzureBlockchainWorkbench/blob/main/WorkbenchFunction.cs)

**Comment by sgiovinetti** [comment]
Thank you @mesgar . My issue is that I cannot add the service principal used by the API to the contract role Device.
It seems to me I registered the SP correctly, look here in AAD app registration the SP is admin.

![image](https://user-images.githubusercontent.com/24455693/107350221-75aa5500-6ac9-11eb-90ce-b5eaa6601dc4.png)
 
If I go in the web app I probbaly see the SP at application level even thought I don't see any dispaly name (perhaps is the first one of the list ???)

![image](https://user-images.githubusercontent.com/24455693/107350725-13058900-6aca-11eb-86f9-fabbcfb4796c.png)

If I go inside the application "Refrigerated Contract" I cannot add any SP. I can add only users...

![image](https://user-images.githubusercontent.com/24455693/107351114-86a79600-6aca-11eb-8b9c-5cafca8bbb8e.png)

How did you manage to regisgter the API endpoint service principal in order to see it within the webapp UI?

By the way tried your API call and I received 400 Bad Request. The inner error in the log says:

```
Fatal error in host: Microsoft.PSharp.Runtime.MachineActionExceptionFilterException: GetPendingContractActionsResponseHandler ---> System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
   at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException)
   at System.Guid.TryParseGuidWithNoStyle(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidStyles flags, GuidResult& result)
   at System.Guid.Parse(ReadOnlySpan`1 input)
   at System.Guid.Parse(String input)
   at Microsoft.Azure.Blockchain.Eth.TxSubmitter.SweeperMachine.GetPendingContractActionsResponseHandler() in /eth-tx-submitter/machines/SweeperMachine.cs:line 95
   at Microsoft.PSharp.Machine.ExecuteAction(CachedAction cachedAction)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Blockchain.Eth.TxSubmitter.EthTxSubmitterService.MainAsync() in /eth-tx-submitter/EthTxSubmitterService.cs:line 50
```

but probably this is due to the fact I cannot add the SP as a Device user like I said at the beginning.

**Comment by mesgar** [comment]
@sgiovinetti 
When you create ABW you already have a Service Principal with admin role.
As explained in  [Original Post](https://medium.com/@malirezaie/how-to-enable-programmatic-interaction-with-azure-blockchain-workbench-apis-56c0d95c79c0) we don't use that account for API. Instead we create a new API user.
Please go to the  [Original Post](https://medium.com/@malirezaie/how-to-enable-programmatic-interaction-with-azure-blockchain-workbench-apis-56c0d95c79c0) and follow the instructions(Step 1: Setting up Azure Active Directory)
For creating user from Postman if you faced any trouble you can refer to my [Japanese](https://qiita.com/iCloudy/items/6e9af60012da64891561) post. Postman setting screen shots are in English.
p.s. If I could find time, I'll make an English version too.

**Comment by sgiovinetti** [comment]
@mesgar thank you for your feedbacks. I missed the user creation and role assignment part using API. Now I have evrything setup like in the documentation you posted but unfortunately the API call to ingest data contnues to fail with 400 Bad Request Invalid data.

![image](https://user-images.githubusercontent.com/24455693/107367488-a5fcee00-6adf-11eb-90fa-b170b98b24b4.png)

![image](https://user-images.githubusercontent.com/24455693/107367584-c75dda00-6adf-11eb-893d-b6eb8b71e418.png)

![image](https://user-images.githubusercontent.com/24455693/107367646-db094080-6adf-11eb-91dc-5807c7d9d393.png)

![image](https://user-images.githubusercontent.com/24455693/107367828-0e4bcf80-6ae0-11eb-8871-b3e8622ad2c3.png)

![image](https://user-images.githubusercontent.com/24455693/107367914-2cb1cb00-6ae0-11eb-9192-fe49dca1fb2e.png)

**Comment by mesgar** [comment]
@sgiovinetti 
Almost there!
This message is a little bit misleading I had the same problem this afternoon.
If you go to Azure portal and check API Log Stream you'll find the real problem. 
![image](https://user-images.githubusercontent.com/10726024/107369866-9d2f0b00-6b25-11eb-8eac-b5faa122c0bf.png)
![image](https://user-images.githubusercontent.com/10726024/107370037-d2d3f400-6b25-11eb-8274-b79af6e1eff2.png)

Mine was:
[dbo].[CreateContractAction], User 3 is not authorized to take this action.

That's why I had to set my API user as owner and device role when creating a new contract. 
![image](https://user-images.githubusercontent.com/10726024/107369252-e3379f00-6b24-11eb-89f5-dbd451449508.png)

Well, ABS and ABW are in public preview and it'll take a long time for Microsoft to GA them.

**Comment by sgiovinetti** [comment]
@mesgar You are right! this was my issue as well. Finally I have fixed it and able to ingest telemetry. Thank you very much for your big help on this. Let's leave the bug open since anyway it looks like the ingestion through message queue doesn't work.

**Comment by mesgar** [comment]
R.I.P ABW
