### ISSUE TITLE
TypeError: callback is not a function:  process.internalTickCallback:next_tick.js:72:19

### ISSUE THREAD

**Issue by dahifi** [Azure-Samples/blockchain#80]
### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Run in WSL: 
`\workbench\blockchain-development-kit\devops\sample-files\truffle test`
also fails with `truffle migrate`

### Any log messages given by the failure
`

/home/user/.nvm/versions/node/v11.2.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128
      callback(error, result);
^
TypeError: callback is not a function
    at /home/user/.nvm/versions/node/v11.2.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/property.js:119:1
    at /home/user/.nvm/versions/node/v11.2.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:89:1
    at /home/user/.nvm/versions/node/v11.2.0/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:225:1
    at /home/user/.nvm/versions/node/v11.2.0/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/home/user/.nvm/versions/node/v11.2.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/user/.nvm/versions/node/v11.2.0/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/home/user/.nvm/versions/node/v11.2.0/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/home/user/.nvm/versions/node/v11.2.0/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/home/user/.nvm/versions/node/v11.2.0/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1098:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
`

### Expected/desired behavior
Not to crash.
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Win10
### Versions
Build 17134.407

### Mention any other details that might be useful
WSL Ubuntu 14.04.5 LTS
Node v11.2.0

Running Ganache, I see several transactions and blocks generated each time I run test or migrate. 

Was able to deploy other Truffle box successfully, so environment appears stable.

**Comment by ali92hm** [comment]
These files have been moved to a new repo under https://github.com/Azure-Samples/blockchain-devkit
